FROM node:12.2.0-alpine

# set working directory
COPY /client /client

# install and cache c/client dependencies
RUN npm update npm
RUN npm install --no-optional --progress=false

# start c/client
CMD [ "npm", "run", "serve" ]
