version: '3.8'

services:
  api:
    build: ./api-db
    container_name: trivia_api
    command: python server.py run -h 0.0.0.0
    volumes:
      - ./api-db/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      
  db:
    image: postgres:13-alpine
    container_name: trivia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=trivia

volumes:
  postgres_data:
